### ISSUE TITLE
Inkscape Error Message

### ISSUE THREAD

**Issue by Limolwali** [paulh-rnd/TabbedBoxMaker#13]
I have successfully installed this and run it on my Mac Laptop. I love it. 
However, despite having installed at least 4 different versions of Inkscape and 5-6 different builds of Python, I either get no response upon clicking apply or the following error:

Inkscape has received additional data from the script executed.  The script did not return an error, but this may indicate the results will not be as expected.
  File "boxmaker.py", line 7

    <!DOCTYPE html>

    ^

SyntaxError: invalid syntax

I am running Windows 10 64 bit and have tried 32 and 64 bit versions of Inkscape  .91 and .92.1 with the following Python Builds:

2.6.5 32&64
2.7.2 
2.7.13 32&64
3.6

I'm at my wits end. I know it has to be a simple fix. Ideas?

**Comment by paulh-rnd** [comment]
Please check the contents of boxmaker.py in Notepad or your favourite text editor and compare it to what you see on [this page](https://github.com/paulh-rnd/TabbedBoxMaker/blob/master/boxmaker.py).  I suspect you have downloaded a corrupt file or somehow got the content mixed with something else (antivirus to blame thinking the .py file was somehow dangerous?), since "<!DOCTYPE html>" should not appear in boxmaker.py anywhere.

Try re-downloading from the Code tab above (Clone or Download > Download ZIP), then extract the files into the extensions folder again and overwrite what's there.  I'm pretty sure that will fix it.

**Comment by paulh-rnd** [comment]
Oh, and I haven't tried 0.92+ yet, it's on my (ever-growing) list of things to do.  And the python interpreter that comes with Inkscape should suffice, there's no need to go installing other versions.

**Comment by Limolwali** [comment]
Thanks for the quick response. I tried all your suggestions on a fresh install of Inkscape .91. Unfortunately, I still get the same error. I'll keep plugging away at it and welcome any more suggestions. I've attached a screenshot, just in case it helps.
The issue occurs when I check the live preview or apply buttons, but, as the shot shows, no lines appear to be generated.
![screenshot_001](https://cloud.githubusercontent.com/assets/7719618/24230757/0e623f60-0f57-11e7-9824-41f1287d9e0a.png)

**Comment by paulh-rnd** [comment]
Strange.  Please paste the contents of boxmaker.py and the location of the file on your disk.  Please note that the file may actually be found in one of two places: 

%APPDATA%\Roaming\inkscape\extensions
C:\Program Files\Inkscape\share\extensions

(Hit Win-R and paste in either of the above paths to find it).  It may be that you have two copies of the file, the corrupt one and the one you replaced.  If you have two, check them both.  If you have one, paste it in here and I'll take a look.

**Comment by Limolwali** [comment]
That did the trick. Didn't occur to me that the extension files might be in two different locations. Thanks for the help. Everything is working perfectly now.
