### ISSUE TITLE
Ability to create dogbones / overcut corners

### ISSUE THREAD

**Issue by cclein** [paulh-rnd/TabbedBoxMaker#3]
It would be great to have the ability to cut these boxes on a CNC machine. creating dogbones / overcutting the corner by the radius of the cutting bit...

Here is a great article on the issue:
http://blog.inventables.com/2014/06/learn-about-milling-inside-corner.html
and some sample code:

https://github.com/vlachoudis/bCNC/blob/master/plugins/box.py

Cheers,

C

**Comment by paulh-rnd** [comment]
Interesting.  I haven't used a CNC mill before and don't currently have any plans to use one... But I'll leave this as an open feature request in case someone else wants to have a go.  I may be making some further enhancements to this later in the year so I may take a look then - it shouldn't be too hard to add this at all.

**Comment by pauloasherring** [comment]
Hey there, I added the dogbone feature, at least for the joinery of the box it self. It is still missing for the dividers and divider keying. I don't know how to work collaboratively in the github or git for that matter, but, if you wish, I could share that.
Best regards and thanks for the awesome, ugly software, hahahahaha.

**Comment by paulh-rnd** [comment]
Hi @cclein, @pauloasherring and @nicolasdb - thanks for your interest in this! It's been a long time coming and tbh I haven't looked at this issue since 2015(!), and somehow I even managed to miss Paulo's comment and yet went ahead recently and built it anyway.  I came back here and realised that the work has already been done 😲 😃 

 @pauloasherring I'd be interested to see how you did the dogbone to see if it is simpler than my approach (which is admittedly just more of an ugly hack job!).  I've implemented it, but it's only working in the very latest build on the beta branch: https://github.com/paulh-rnd/TabbedBoxMaker/tree/beta.  What's more, I still don't have a mill I can test this on, and my laser cutter is *still* in storage since moving 18 months ago 😢 

Please test and provide feedback!  As per Paulo's comment, my one only deals with the tabbed joints and not the divider slots or keying.  Also there are a few issues with various options and layouts that I'm aware of (eg. "Rotate symmetrical" not working with fewer than 6 sides), hopefully I'll get them fixed before the 1.0 final release.

Thanks again for your support and sorry for taking so long to get to this feature request!

**Comment by paulh-rnd** [comment]
This change has now been merged to master. As I didn't get any feedback on this, I assume either nobody tested it or you were happy with it! :D

Thanks again for the suggestion, I hope this works for you.
