### ISSUE TITLE
Finger size doesn't appear to mate 

### ISSUE THREAD

**Issue by jkwilborn** [paulh-rnd/TabbedBoxMaker#47]
I have created a box and saved it as an SVG.  I read it into Lightburn and when I preview it, it's clear the parts won't fit.  I ran a short test of two parts and they don't match.  Here is the Inkscape screenshot

![inkscape-box](https://user-images.githubusercontent.com/3381434/127584155-6cf670d9-b191-42c0-8fb9-67b36767a6ca.png)

Saved as SVG  and read into Lightburn.  This is the edit screen.  I added the circle for your reference when I zoom in.
Lightburn 'edit' window

![lightburn-box](https://user-images.githubusercontent.com/3381434/127584255-7ee6b9f8-9cce-4d40-97ce-a57b7af73b57.png)

Looks good, but when I do the 'preview' to show the cut it's pretty clear the parts don't mesh.

![lightburn-preview](https://user-images.githubusercontent.com/3381434/127584307-76fbfd97-d980-40fa-9f96-0a56d1dc01d8.png)

Is it something I did or didn't do?  First time with this plugin...

**Comment by paulh-rnd** [comment]
Hey, thanks for stopping by to ask a question! You are right that on the surface of it it looks like the parts won't fit. The key is in the kerf setting:

Kerf is the width of cut: for a laser cutter this is typically very small, often 0.1-0.2mm. For a CNC router it is as big as the diameter of the router bit, which could be 4-12mm - or more. Because both types of cut are "subtractive", you end up with a piece that is marginally smaller than the piece that you designed: with your settings perfectly calibrated, each cut will remove (kerf/2) material.

So what you're seeing is that the finger joints are fatter than they need to be on the finished part: If you measure them, the fingers should in theory be fatter than the gap they need to fit in by (kerf x 2) - because there are 4 cuts to make, two on each face of the interlocking fingers.

You can test this by setting the kerf to zero: the pieces should mesh perfectly on screen, but when you cut it, you'll notice the joint is very loose.

It can be a case of trial and error to get the kerf exactly right for a perfect fit, but if you ask me it's all part of the joy of laser cutting 😉

Good luck!

**Comment by jkwilborn** [comment]
I tried it without the kerf, set to zero, still didn't fit..  Thanks for your time. Take care :)

**Comment by paulh-rnd** [comment]
Sorry, I didn't mean to dismiss the issue if there's a reproducible bug. While you didn't give me any measurements of the finger joints they looked about right to me for the kerf in your screenshot (0.215mm). If you can give me an example of what you're seeing and what you expect, including full measurements, I'll check it out and let you know if it's expected. The zero kerf setting is the best example but it's worth trying with a non-zero setting and measuring that as well.

Finally, you said you did a test cut? If the joint is too tight it usually means that the actual kerf is smaller than the one you used to generate the box. For reference, I usually use a kerf of 0.125mm so 0.215mm for me would definitely yield a joint that would be too tight, but it may well be right for your machine - actual kerf depends on a number of settings including how well calibrated and focused your laser is, cut speed, power, what material you are cutting and more.

I'm happy to reopen this bug and look at it if you can give me a little more info on what you've tried and what the results were.

**Comment by jkwilborn** [comment]
I used several of these on-line box making sites to generate a box for my
modem.  It was frustrating to generate something and find pieces missing
and things not lining up.  The material has a measured kerf of .215 mm.
This was measured by the 10 cut measure gap method.  I've used it on ply
and acrylic successfully.

I spent about 3 to 4 hours with different settings and finally gave up.
Went through at least 4 online box generators.  Managed to find at least
one bug out of the list, if this isn't one.

I moved on to another site that seems to generate the same box with these
same numbers and others successfully.

Thanks, sorry to bother you.

Take care.

Jack Wilborn
