### ISSUE TITLE
Width of line too wide

### ISSUE THREAD

**Issue by ZenithDK** [paulh-rnd/TabbedBoxMaker#8]
I use an Epilog laser cutter, and that requires the lines to be "hairline" (to use the term from Corel).
I think the line width needs to be 0.002 mm to make the laser cutter understand that it needs to cut and not vectorize: http://support.epiloglaser.com/article/8205/29827/cutting-and-engraving-different-line-weights

Not sure if this is really simple to change, or if it requires further changes to the code.

**Comment by applemuncy** [comment]
Don't take what I say here as absolute. As I comb though TabbedMaker code only in the drawCircle def is line width set and there it is set to one.
But as I understand it, Inkscape just uses its default width of one pixel. 

I think you are in error when you say the line width needs to be 0.002 mm . That would be very thin line indeed at 0.000078 inches. I read in the link you supplied they are using inches.

So something real useful in Inkscape, make a selection and then click Object on the top edge of the program, then pick "fill and stroke..".
That should open a pane with tabs. the far right tab "stroke style" lets you change the line width.

I hope that helps.

**Comment by paulh-rnd** [comment]
Thanks for the report @ZenithDK.

I've done a bit of research and it looks like 0.001-0.003" are reliable and commonly used cutting widths for all Epilogs, regardless of resolution you use.  See [here](http://support.epiloglaser.com/article/8205/29827/cutting-and-engraving-different-line-weights) for details.  A lot of people seem to use 0.001", I think simply because that's the default for CorelDraw's "Hairline" width, but that looks a little fine in Inkscape so I'm going with 0.002".  I've added a "Line thickness" parameter with options "Default" (1px) and "Hairline" (0.002").  Please let me know if this works for you.

No Chinese laser cutters that I know of distinguish between line sizes (only colour), so it's never been a problem for me (I have yet to use an Epilog, sadly).  Please particularly test schroff boxes if they are of interest to you, I don't have any personal use for them myself :)

**Comment by ZenithDK** [comment]
I don't cut Schroff boxes by the way - I don't know what they are :-)
Enclosures for some type of hardware I was assuming.

Thanks for adding this, will make my life a tad easier.
